import { describe, expect, it } from 'vitest'
import { loadBundledRuntimeData } from '../../data'; import type { Person, SourceReference } from '../entities'; import { parseMapUrlState, serializeMapUrlState } from '../../url'
import { syntheticRuntime } from '../../test/syntheticRuntime'
import { aggregatePersonSources, buildPersonPresentation, buildPersonPresentations, getActivePersonPlaceRelationships, getPersonMinZoom, isPersonAliveAtYear, isPersonNormallyVisible, PERSON_RELATIONSHIP_PRIORITY } from './personSelectors'
import { buildPersonLocationAggregates } from './personAggregation'; import { buildPersonFeatureCollection } from './personGeoJson'; import { createPersonSelection, PERSON_SELECTION_HISTORY_MODE, selectedPersonId, withSelectedPerson, withSelectedPersonYear, withoutImplementedMapSelection } from './selection'
const dataset = syntheticRuntime(loadBundledRuntimeData()); const alpha = dataset.people.find((p) => p.id === 'synthetic-alpha-person') as Person; const beta = dataset.people.find((p) => p.id === 'synthetic-beta-person') as Person; const gamma = dataset.people.find((p) => p.id === 'synthetic-gamma-person') as Person
const at = (person: Person, year = -334) => buildPersonPresentation(person, dataset, year)
describe('person life and relationships', () => {
  it('loads three synthetic people', () => expect(dataset.people).toHaveLength(3))
  it.each([[-500,true], [10,true], [-501,false], [11,false]] as const)('alpha alive at %i is %s', (year, expected) => expect(isPersonAliveAtYear(alpha, year)).toBe(expected))
  it('unknown life end is explicit', () => { const p=structuredClone(alpha); p.life.yearTo=null; expect(isPersonAliveAtYear(p,-334)).toBe(false) })
  it.each([[-350,true],[-330,true],[-351,false],[-329,false]] as const)('campaign relationship at %i is %s', (year, expected) => expect(getActivePersonPlaceRelationships(alpha,year).some((r)=>r.relationType==='campaign')).toBe(expected))
  it('birth is not permanent', () => expect(getActivePersonPlaceRelationships(alpha,-499).some((r)=>r.relationType==='birth')).toBe(false))
  it('gamma is alive but unmapped at default year', () => expect(at(gamma)).toMatchObject({ alive:true, mapped:false, activeLocations:[] }))
  it('outside-life selection stays present', () => expect(at(gamma,-100)).toMatchObject({ alive:false, mapped:false }))
  it('alpha changes primary place across periods', () => { expect(at(alpha,-334).primaryLocation?.placeId).toBe('synthetic-alpha-place'); expect(at(alpha,-320).primaryLocation?.placeId).toBe('synthetic-beta-place') })
  it('retains all simultaneous relationships and priority', () => { const p=structuredClone(alpha); p.places.push({ ...structuredClone(p.places[1]), relationType:'residence', placeId:'synthetic-beta-place' }); const result=at(p,-334); expect(result.activeLocations).toHaveLength(2); expect(result.primaryLocation?.relationType).toBe('campaign') })
  it('documents deterministic relationship priority', () => expect(PERSON_RELATIONSHIP_PRIORITY).toEqual(['campaign','rule','activity','residence','visit','birth','death','unknown']))
  it('unresolved place fails safely', () => expect(buildPersonPresentation(alpha,{...dataset,places:[]},-334).primaryLocation).toMatchObject({placeName:null,coordinates:null}))
  it('reuses the period-appropriate Place name', () => { const p=structuredClone(alpha); p.places[1].period={yearFrom:-450,yearTo:-450}; expect(at(p,-450).activeLocations[0]?.placeName).toBe('Synthetic Alpha Old Name') })
  it('uses no offset or person coordinate', () => expect(at(alpha).primaryLocation?.coordinates).toEqual([28,37]))
})
describe('importance and aggregation', () => {
  it.each([[1,5.5],[2,4.5],[3,3.5],[4,2.5],[5,1.5]] as const)('importance %i starts at zoom %f',(i,z)=>expect(getPersonMinZoom(i)).toBe(z))
  it('important mapped person visible',()=>expect(isPersonNormallyVisible(at(alpha),3.5,true)).toBe(true))
  it('low importance hidden then visible',()=>{expect(isPersonNormallyVisible(at(beta),3.5,true)).toBe(false);expect(isPersonNormallyVisible(at(beta),4.5,true)).toBe(true)})
  it('unmapped and outside life hidden',()=>{expect(isPersonNormallyVisible(at(gamma),7,true)).toBe(false);expect(isPersonNormallyVisible(at(gamma,-100),7,true)).toBe(false)})
  it('aggregates alpha and beta at same Place ID',()=>{const a=buildPersonLocationAggregates(buildPersonPresentations(dataset,-334),5,true,null);expect(a[0]).toMatchObject({placeId:'synthetic-alpha-place',visibleCount:2,highestImportance:3,aggregate:true})})
  it('orders members by importance then name',()=>expect(buildPersonLocationAggregates(buildPersonPresentations(dataset,-334),5,true,null)[0]?.members.map(m=>m.id)).toEqual(['synthetic-alpha-person','synthetic-beta-person']))
  it('changes aggregation with year',()=>expect(buildPersonLocationAggregates(buildPersonPresentations(dataset,-320),5,true,null).map(a=>a.visibleCount)).toEqual([1,1]))
  it('respects zoom thresholds',()=>expect(buildPersonLocationAggregates(buildPersonPresentations(dataset,-334),3.5,true,null)[0]?.members.map(m=>m.id)).toEqual(['synthetic-alpha-person']))
  it('selected zoom-hidden member remains',()=>expect(buildPersonLocationAggregates(buildPersonPresentations(dataset,-334),3.5,true,beta.id)[0]?.visibleCount).toBe(2))
  it('disabled layer retains only selected mapped person',()=>expect(buildPersonLocationAggregates(buildPersonPresentations(dataset,-334),5,false,beta.id)[0]?.members.map(m=>m.id)).toEqual([beta.id]))
  it('selected unmapped person has no aggregate',()=>expect(buildPersonLocationAggregates(buildPersonPresentations(dataset,-334),5,false,gamma.id)).toEqual([]))
  it('single member is individual',()=>expect(buildPersonLocationAggregates(buildPersonPresentations(dataset,-334),3.5,true,null)[0]?.aggregate).toBe(false))
})
describe('person GeoJSON',()=>{
  const aggregates=buildPersonLocationAggregates(buildPersonPresentations(dataset,-334),5,true,null); const geo=buildPersonFeatureCollection(aggregates)
  it('is valid feature collection',()=>expect(geo.type).toBe('FeatureCollection'))
  it('preserves longitude latitude',()=>expect(geo.features[0]?.geometry.coordinates).toEqual([28,37]))
  it('has stable deterministic ID',()=>expect(geo.features[0]?.id).toBe('person-location-synthetic-alpha-place'))
  it('retains aggregate/count/importance',()=>expect(geo.features[0]?.properties).toMatchObject({aggregate:true,visibleCount:2,highestImportance:3,active:true}))
  it('retains selected state',()=>{const selected=buildPersonFeatureCollection(buildPersonLocationAggregates(buildPersonPresentations(dataset,-334),5,true,alpha.id));expect(selected.features[0]?.properties.selected).toBe(true)})
  it('contains compact properties only',()=>{const s=JSON.stringify(geo.features[0]?.properties);expect(s).not.toContain('sourceRefs');expect(s).not.toContain('roles');expect(s).not.toContain('life')})
  it('is deterministic',()=>expect(buildPersonFeatureCollection([...aggregates].reverse())).toEqual(geo))
})
describe('relations evidence and actions',()=>{
  it('resolves polity event and journey',()=>expect(at(alpha)).toMatchObject({associatedPolities:[{name:'Synthetic Alpha Polity'}],relatedEvents:[{name:'Synthetic Alpha Event'}],relatedJourneys:[{name:'Synthetic Alpha Journey'}]}))
  it('excludes unrelated events',()=>expect(at(alpha).relatedEvents.some(e=>e.id==='synthetic-unknown-event')).toBe(false))
  it('fails unresolved relations safely',()=>{const p=buildPersonPresentation(alpha,{...dataset,polities:[],events:[],journeys:[]},-334);expect(p.associatedPolities[0]?.name).toBeNull();expect(p.relatedEvents[0]?.name).toBeNull()})
  it('prioritizes active relationship evidence',()=>expect(at(alpha).sources.resolved[0]?.reference.locator).toBe('Synthetic alpha campaign'))
  it('includes person evidence',()=>expect(at(alpha).sources.resolved.some(x=>x.reference.locator==='Synthetic alpha person')).toBe(true))
  it('excludes inactive birth evidence',()=>expect(at(alpha).sources.resolved.some(x=>x.reference.locator==='Synthetic birth relationship')).toBe(false))
  it('deduplicates references',()=>{const p=structuredClone(alpha);p.sourceRefs.push(structuredClone(p.sourceRefs[0]));expect(aggregatePersonSources(p,[],dataset.sources).resolved).toHaveLength(1)})
  it('retains distinct locators',()=>{const p=structuredClone(alpha);const r:SourceReference={sourceId:p.sourceRefs[0].sourceId,locator:'Other synthetic'};p.sourceRefs.push(r);expect(aggregatePersonSources(p,[],dataset.sources).resolved).toHaveLength(2)})
  it('reports unresolved sources',()=>expect(aggregatePersonSources(alpha,[],[]).unresolvedSourceIds).toEqual(['synthetic-fixture-source']))
  it('computes life and mapped actions',()=>expect(at(gamma,-500)).toMatchObject({firstLifeYear:-400,nearestLifeYear:-400,firstMappedYear:-280,nearestMappedYear:-280}))
  it('nearest mapped after period',()=>expect(at(gamma,-100).nearestMappedYear).toBe(-260))
})
describe('person selection URL',()=>{
  const state=parseMapUrlState('?year=-334&lat=37&lng=28&zoom=4&layers=territories,places,people,events&collection=synthetic-alpha-collection'); const selected=withSelectedPerson(state,alpha.id)
  it('creates typed selection',()=>expect(createPersonSelection(alpha.id)).toEqual({type:'person',id:alpha.id}))
  it('extracts person only',()=>{expect(selectedPersonId(selected.selectedEntity)).toBe(alpha.id);expect(selectedPersonId({type:'event',id:'synthetic-alpha-event'})).toBeNull()})
  it('preserves URL state',()=>expect(selected).toMatchObject({year:-334,latitude:37,longitude:28,zoom:4,collectionId:'synthetic-alpha-collection'}))
  it('preserves unrelated params',()=>expect(serializeMapUrlState(selected,'?owner=check').get('owner')).toBe('check'))
  it('uses push',()=>expect(PERSON_SELECTION_HISTORY_MODE).toBe('push'))
  it.each(['place','polity','event','person'] as const)('clears %s',(type)=>expect(withoutImplementedMapSelection({...state,selectedEntity:{type,id:'synthetic-id'}}).selectedEntity).toBeNull())
  it('preserves journey',()=>{const s={...state,selectedEntity:{type:'journey',id:'synthetic-alpha-journey'} as const};expect(withoutImplementedMapSelection(s)).toBe(s)})
  it('restores from URL',()=>expect(parseMapUrlState(serializeMapUrlState(selected)).selectedEntity).toEqual({type:'person',id:alpha.id}))
  it('year action preserves selection viewport',()=>expect(withSelectedPersonYear(selected,-320)).toMatchObject({year:-320,latitude:37,longitude:28,selectedEntity:{type:'person',id:alpha.id}}))
  it('rejects year zero',()=>expect(()=>withSelectedPersonYear(selected,0)).toThrow())
  it('all fixtures remain synthetic',()=>expect(dataset.people.every(p=>p.id.startsWith('synthetic-')&&`${p.defaultName} ${p.summary??''}`.toLowerCase().includes('synthetic'))).toBe(true))
})
